// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyNice
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyNice.1f9c7576-432f-484b-bfd1-4ce7f6f4ccf4";
        public const string Name = "Copy Nice";
        public const string Description = @"Strips leading indentation when copying to the clipboard. This fixes the issue of tangled code when pasting code into an email, IM, or elsewhere.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "copy, paste, formatting, clipboard";
    }
}
